import '../../domain/error/failure.dart';
import '../../domain/models/bookmark.dart';
import '../../domain/models/result.dart';
import '../../domain/repository/bookmark_repository.dart';
import 'database_service.dart';

/// Default implementation of BookmarkRepository.
class DefaultBookmarkRepository implements BookmarkRepository {
  final DatabaseService _databaseService;

  DefaultBookmarkRepository(this._databaseService);

  @override
  Stream<List<Bookmark>> getAllBookmarksStream() =>
      _databaseService.getAllBookmarksStream();

  @override
  Future<Result<List<Bookmark>>> getAllBookmarks() => Result.runCatching(
        () => _databaseService.getAllBookmarks(),
        failureMapper: (e) => DatabaseFailure('Failed to fetch bookmarks', e),
      );

  @override
  Future<Result<Bookmark?>> getBookmarkById(String id) => Result.runCatching(
        () => _databaseService.getBookmarkById(id),
        failureMapper: (e) => DatabaseFailure('Failed to fetch bookmark $id', e),
      );

  @override
  Future<Result<List<Bookmark>>> getBookmarksForChapter(int chapterNumber) =>
      Result.runCatching(
        () => _databaseService.getBookmarksForChapter(chapterNumber),
        failureMapper: (e) => DatabaseFailure(
            'Failed to fetch bookmarks for chapter $chapterNumber', e),
      );

  @override
  Future<Result<Bookmark?>> getBookmarkForVerse(
          int chapterNumber, int verseNumber) =>
      Result.runCatching(
        () => _databaseService.getBookmarkForVerse(chapterNumber, verseNumber),
        failureMapper: (e) => DatabaseFailure(
            'Failed to fetch bookmark for $chapterNumber:$verseNumber', e),
      );

  @override
  Future<Result<Bookmark>> addBookmark({
    required int chapterNumber,
    required int verseNumber,
    required int pageNumber,
    String note = '',
    List<String> tags = const [],
  }) =>
      Result.runCatching(
        () => _databaseService.addBookmark(
          Bookmark(
            id: '', // Will be generated by DB
            chapterNumber: chapterNumber,
            verseNumber: verseNumber,
            pageNumber: pageNumber,
            note: note,
            tags: tags,
            timestamp: DateTime.now().millisecondsSinceEpoch,
          ),
        ),
        failureMapper: (e) => DatabaseFailure('Failed to add bookmark', e),
      );

  @override
  Future<Result<void>> updateBookmarkNote(String id, String note) =>
      Result.runCatching(
        () => _databaseService.updateBookmarkNote(id, note),
        failureMapper: (e) =>
            DatabaseFailure('Failed to update bookmark note', e),
      );

  @override
  Future<Result<void>> updateBookmarkTags(String id, List<String> tags) =>
      Result.runCatching(
        () => _databaseService.updateBookmarkTags(id, tags),
        failureMapper: (e) =>
            DatabaseFailure('Failed to update bookmark tags', e),
      );

  @override
  Future<Result<void>> deleteBookmark(String id) => Result.runCatching(
        () => _databaseService.deleteBookmark(id),
        failureMapper: (e) => DatabaseFailure('Failed to delete bookmark $id', e),
      );

  @override
  Future<Result<void>> deleteBookmarkForVerse(
          int chapterNumber, int verseNumber) =>
      Result.runCatching(
        () => _databaseService.deleteBookmarkForVerse(chapterNumber, verseNumber),
        failureMapper: (e) => DatabaseFailure(
            'Failed to delete bookmark for $chapterNumber:$verseNumber', e),
      );

  @override
  Future<Result<void>> deleteAllBookmarks() => Result.runCatching(
        () => _databaseService.deleteAllBookmarks(),
        failureMapper: (e) =>
            DatabaseFailure('Failed to delete all bookmarks', e),
      );

  @override
  Future<Result<bool>> isVerseBookmarked(int chapterNumber, int verseNumber) =>
      Result.runCatching(
        () => _databaseService.isVerseBookmarked(chapterNumber, verseNumber),
        failureMapper: (e) => DatabaseFailure(
            'Failed to check bookmark for $chapterNumber:$verseNumber', e),
      );

  @override
  Future<Result<List<Bookmark>>> searchBookmarks(String query) =>
      Result.runCatching(
        () => _databaseService.searchBookmarks(query),
        failureMapper: (e) =>
            DatabaseFailure('Bookmark search failed for query: $query', e),
      );
}
